syscmd(`docker run stevemeisner/node8-python2-pip-yarn-alpine35 -c "npm -v"')
syscmd(`docker run stevemeisner/node8-python2-pip-yarn-alpine35 -c "node -v"')
syscmd(`docker run stevemeisner/node8-python2-pip-yarn-alpine35 -c "webpack -v"')
syscmd(`docker run stevemeisner/node8-python2-pip-yarn-alpine35 -c "yarn -V"')
syscmd(`docker run stevemeisner/node8-python2-pip-yarn-alpine35 -c "gpg --version|head -1"')
syscmd(`docker run stevemeisner/node8-python2-pip-yarn-alpine35 -c "rhash --version"')
